// BHaH core header file, automatically generated from cuda.output_BHaH_defines_h,
//    DO NOT EDIT THIS FILE BY HAND.

// Device storage for grid parameters
__constant__ params_struct d_params;
// Device storage for commondata
__constant__ commondata_struct d_commondata;
// Device storage for grid function parity
__constant__ int8_t d_evol_gf_parity[24];
cudaStream_t streams[nstreams];
size_t GPU_N_SMS;
__constant__ REAL d_gridfunctions_wavespeed[NUM_EVOL_GFS];
__constant__ REAL d_gridfunctions_f_infinity[NUM_EVOL_GFS];
